### ISSUE TITLE
Can't validate cluster after creation

### ISSUE THREAD

**Issue by smithkb** [pahud/kops-cn#2]
I've been looking at this cluster creation repo today, and I attempted to create a cluster in `cn-north-1` region following all the instructions in Readme.md. I was able to run all the commands successfully. Cluster creation was successful, but when attempting to use kubectl to view the nodes or kops to validate, I get an error listing the nodes:
INPUT
`kops validate cluster`

OUTPUT
`unexpected error during validation: error listing nodes: Get https://<node>.cn-north-1.elb.amazonaws.com.cn/api/v1/nodes: EOF`

I'm running these commands from inside the US. Do I need to be running validation inside of China? It looks to me like my cluster is unable to get the container images needed to actually run k8s.

**Comment by pahud** [comment]
Hi @smithkb  thanks for the feedback. Actually you don't need to run this in China, I run my `kops` commands actually in Cloud9 of `us-west-2`.  I will try to validate the cluster creation from another AWS account to make sure it works. Will let you know if I have any updates.

**Comment by pahud** [comment]
Hi @smithkb 

By default, you need to file for ICP Recordal or ICP License if I want to host public content on AWS China (Beijing) Region or China (Ningxia) Region, otherwise the HTTP/HTTPS port on ELB will not be open, even the security group is open.

Your error indicates that the client can't reach out to the ELB port HTTPS:443. Please make sure you have completed the necessary procedure mentioned above.

check the official FAQ here: https://www.amazonaws.cn/en/about-aws/china/faqs/?nc1=f_ls#new%20step

**Comment by smithkb** [comment]
We do have an ICP License and have other content hosted in AWS. I'll validate on my end that this is in fact the case. Thanks for the quick response. It looks to me like the containers for running k8s aren't actually downloading and running for some reason.

**Comment by pahud** [comment]
Hi

There is an issue https://github.com/pahud/kops-cn/issues/3 that may be releated to this one. I am investigating on it.

**Comment by pahud** [comment]
Hi @smithkb 

Please try again with the latest  `spec.yml` as we changed the ECR from `cn-northwest-1` to `cn-north-1`

https://github.com/pahud/kops-cn/blob/04f7802a89cd47eda2cf265274573c5ce69f752f/spec.yml#L3

**Comment by smithkb** [comment]
That solved it.

**Comment by pahud** [comment]
@smithkb Happy to know that. Let me know if you have any other questions in terms of this repo. Thanks!
