### ISSUE TITLE
about fileRepository

### ISSUE THREAD

**Issue by sjkyspa** [pahud/kops-cn#6]
under the spec.yml config like below
fileRepository: https://s3.cn-north-1.amazonaws.com.cn/kops-bjs/fileRepository/

how to prepare a file repository?

**Comment by pahud** [comment]
this is my preliminary mirror script for fileRepository
https://github.com/pahud/kops-cn/blob/master/mirror/fileRepository/mirro.sh

I run this script in EC2 from `us-west-2` region to pull files to local and `s3 sync` to S3 bucket(`s3://kops-bjs`) in `cn-north-1`

FYR
